[env:feather_esp32s3_tft]
platform = espressif32
board = adafruit_feather_esp32s3_tft
framework = arduino
monitor_speed = 115200
lib_deps =
    gin66/FastAccelStepper@^0.30.6

; Usa espflash (Rust) para fazer o upload em vez do esptool padrão
upload_protocol = custom
upload_command = espflash flash --monitor $SOURCE
