[env:feather_esp32s3_tft]
platform = espressif32
board = adafruit_feather_esp32s3_tft
framework = arduino
monitor_speed = 115200
monitor_echo = yes
lib_deps =
    gin66/FastAccelStepper@^0.30.6
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit ST7789@^1.10.4
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.16.1

upload_port = /dev/ttyACM0
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
